name: freesnow
version: '2'



services:
#  server:
#    build: .
#    ports: "8080:8080"

  postgres:
    image: postgis/postgis
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: freesnow_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
     # - /Users/matthewdavenport/Work/postgres/data:/var/lib/postgresql/data